//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.ApplicantService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicantService.IApplicant")]
    public interface IApplicant {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/AddApplicantEducationResponse")]
        void AddApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/AddApplicantEducationResponse")]
        System.Threading.Tasks.Task AddApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantEducationResponse")]
        CareerCloud.Pocos.ApplicantEducationPoco GetSingleApplicantEducation(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco> GetSingleApplicantEducationAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantEducationResponse")]
        CareerCloud.Pocos.ApplicantEducationPoco[] GetAllApplicantEducation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco[]> GetAllApplicantEducationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantEducationResponse")]
        void UpdateApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantEducationResponse")]
        System.Threading.Tasks.Task UpdateApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantEducationResponse")]
        void RemoveApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantEducationResponse")]
        System.Threading.Tasks.Task RemoveApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/AddApplicantJobApplicationResponse")]
        void AddApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/AddApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task AddApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantJobApplicationResponse")]
        CareerCloud.Pocos.ApplicantJobApplicationPoco GetSingleApplicantJobApplication(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco> GetSingleApplicantJobApplicationAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantJobApplicationResponse")]
        CareerCloud.Pocos.ApplicantJobApplicationPoco[] GetAllApplicantJobApplication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco[]> GetAllApplicantJobApplicationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantJobApplicationResponse")]
        void UpdateApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task UpdateApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantJobApplicationResponse")]
        void RemoveApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task RemoveApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/AddApplicantProfileResponse")]
        void AddApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/AddApplicantProfileResponse")]
        System.Threading.Tasks.Task AddApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantProfileResponse")]
        CareerCloud.Pocos.ApplicantProfilePoco GetSingleApplicantProfile(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco> GetSingleApplicantProfileAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantProfileResponse")]
        CareerCloud.Pocos.ApplicantProfilePoco[] GetAllApplicantProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco[]> GetAllApplicantProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantProfileResponse")]
        void UpdateApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantProfileResponse")]
        System.Threading.Tasks.Task UpdateApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantProfileResponse")]
        void RemoveApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantProfileResponse")]
        System.Threading.Tasks.Task RemoveApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantResume", ReplyAction="http://tempuri.org/IApplicant/AddApplicantResumeResponse")]
        void AddApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantResume", ReplyAction="http://tempuri.org/IApplicant/AddApplicantResumeResponse")]
        System.Threading.Tasks.Task AddApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantResumeResponse")]
        CareerCloud.Pocos.ApplicantResumePoco GetSingleApplicantResume(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantResumeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco> GetSingleApplicantResumeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantResumeResponse")]
        CareerCloud.Pocos.ApplicantResumePoco[] GetAllApplicantResume();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantResumeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco[]> GetAllApplicantResumeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantResume", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantResumeResponse")]
        void UpdateApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantResume", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantResumeResponse")]
        System.Threading.Tasks.Task UpdateApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantResume", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantResumeResponse")]
        void RemoveApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantResume", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantResumeResponse")]
        System.Threading.Tasks.Task RemoveApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/AddApplicantSkillResponse")]
        void AddApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/AddApplicantSkillResponse")]
        System.Threading.Tasks.Task AddApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantSkillResponse")]
        CareerCloud.Pocos.ApplicantSkillPoco GetSingleApplicantSkill(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco> GetSingleApplicantSkillAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantSkillResponse")]
        CareerCloud.Pocos.ApplicantSkillPoco[] GetAllApplicantSkill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco[]> GetAllApplicantSkillAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantSkillResponse")]
        void UpdateApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantSkillResponse")]
        System.Threading.Tasks.Task UpdateApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantSkillResponse")]
        void RemoveApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantSkillResponse")]
        System.Threading.Tasks.Task RemoveApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/AddApplicantWorkHistoryResponse")]
        void AddApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/AddApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task AddApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistoryResponse")]
        CareerCloud.Pocos.ApplicantWorkHistoryPoco GetSingleApplicantWorkHistory(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco> GetSingleApplicantWorkHistoryAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantWorkHistoryResponse")]
        CareerCloud.Pocos.ApplicantWorkHistoryPoco[] GetAllApplicantWorkHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco[]> GetAllApplicantWorkHistoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantWorkHistoryResponse")]
        void UpdateApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task UpdateApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantWorkHistoryResponse")]
        void RemoveApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task RemoveApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicantChannel : CareerCloud.UnitTests.Assignment5.ApplicantService.IApplicant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicantClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.ApplicantService.IApplicant>, CareerCloud.UnitTests.Assignment5.ApplicantService.IApplicant {
        
        public ApplicantClient() {
        }
        
        public ApplicantClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicantClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicantClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicantClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] items) {
            base.Channel.AddApplicantEducation(items);
        }
        
        public System.Threading.Tasks.Task AddApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] items) {
            return base.Channel.AddApplicantEducationAsync(items);
        }
        
        public CareerCloud.Pocos.ApplicantEducationPoco GetSingleApplicantEducation(string id) {
            return base.Channel.GetSingleApplicantEducation(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco> GetSingleApplicantEducationAsync(string id) {
            return base.Channel.GetSingleApplicantEducationAsync(id);
        }
        
        public CareerCloud.Pocos.ApplicantEducationPoco[] GetAllApplicantEducation() {
            return base.Channel.GetAllApplicantEducation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco[]> GetAllApplicantEducationAsync() {
            return base.Channel.GetAllApplicantEducationAsync();
        }
        
        public void UpdateApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] items) {
            base.Channel.UpdateApplicantEducation(items);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] items) {
            return base.Channel.UpdateApplicantEducationAsync(items);
        }
        
        public void RemoveApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] items) {
            base.Channel.RemoveApplicantEducation(items);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] items) {
            return base.Channel.RemoveApplicantEducationAsync(items);
        }
        
        public void AddApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos) {
            base.Channel.AddApplicantJobApplication(pocos);
        }
        
        public System.Threading.Tasks.Task AddApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos) {
            return base.Channel.AddApplicantJobApplicationAsync(pocos);
        }
        
        public CareerCloud.Pocos.ApplicantJobApplicationPoco GetSingleApplicantJobApplication(string id) {
            return base.Channel.GetSingleApplicantJobApplication(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco> GetSingleApplicantJobApplicationAsync(string id) {
            return base.Channel.GetSingleApplicantJobApplicationAsync(id);
        }
        
        public CareerCloud.Pocos.ApplicantJobApplicationPoco[] GetAllApplicantJobApplication() {
            return base.Channel.GetAllApplicantJobApplication();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco[]> GetAllApplicantJobApplicationAsync() {
            return base.Channel.GetAllApplicantJobApplicationAsync();
        }
        
        public void UpdateApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos) {
            base.Channel.UpdateApplicantJobApplication(pocos);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos) {
            return base.Channel.UpdateApplicantJobApplicationAsync(pocos);
        }
        
        public void RemoveApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos) {
            base.Channel.RemoveApplicantJobApplication(pocos);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] pocos) {
            return base.Channel.RemoveApplicantJobApplicationAsync(pocos);
        }
        
        public void AddApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] pocos) {
            base.Channel.AddApplicantProfile(pocos);
        }
        
        public System.Threading.Tasks.Task AddApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] pocos) {
            return base.Channel.AddApplicantProfileAsync(pocos);
        }
        
        public CareerCloud.Pocos.ApplicantProfilePoco GetSingleApplicantProfile(string id) {
            return base.Channel.GetSingleApplicantProfile(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco> GetSingleApplicantProfileAsync(string id) {
            return base.Channel.GetSingleApplicantProfileAsync(id);
        }
        
        public CareerCloud.Pocos.ApplicantProfilePoco[] GetAllApplicantProfile() {
            return base.Channel.GetAllApplicantProfile();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco[]> GetAllApplicantProfileAsync() {
            return base.Channel.GetAllApplicantProfileAsync();
        }
        
        public void UpdateApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] pocos) {
            base.Channel.UpdateApplicantProfile(pocos);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] pocos) {
            return base.Channel.UpdateApplicantProfileAsync(pocos);
        }
        
        public void RemoveApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] pocos) {
            base.Channel.RemoveApplicantProfile(pocos);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] pocos) {
            return base.Channel.RemoveApplicantProfileAsync(pocos);
        }
        
        public void AddApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] pocos) {
            base.Channel.AddApplicantResume(pocos);
        }
        
        public System.Threading.Tasks.Task AddApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] pocos) {
            return base.Channel.AddApplicantResumeAsync(pocos);
        }
        
        public CareerCloud.Pocos.ApplicantResumePoco GetSingleApplicantResume(string id) {
            return base.Channel.GetSingleApplicantResume(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco> GetSingleApplicantResumeAsync(string id) {
            return base.Channel.GetSingleApplicantResumeAsync(id);
        }
        
        public CareerCloud.Pocos.ApplicantResumePoco[] GetAllApplicantResume() {
            return base.Channel.GetAllApplicantResume();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco[]> GetAllApplicantResumeAsync() {
            return base.Channel.GetAllApplicantResumeAsync();
        }
        
        public void UpdateApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] pocos) {
            base.Channel.UpdateApplicantResume(pocos);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] pocos) {
            return base.Channel.UpdateApplicantResumeAsync(pocos);
        }
        
        public void RemoveApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] pocos) {
            base.Channel.RemoveApplicantResume(pocos);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] pocos) {
            return base.Channel.RemoveApplicantResumeAsync(pocos);
        }
        
        public void AddApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] pocos) {
            base.Channel.AddApplicantSkill(pocos);
        }
        
        public System.Threading.Tasks.Task AddApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] pocos) {
            return base.Channel.AddApplicantSkillAsync(pocos);
        }
        
        public CareerCloud.Pocos.ApplicantSkillPoco GetSingleApplicantSkill(string id) {
            return base.Channel.GetSingleApplicantSkill(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco> GetSingleApplicantSkillAsync(string id) {
            return base.Channel.GetSingleApplicantSkillAsync(id);
        }
        
        public CareerCloud.Pocos.ApplicantSkillPoco[] GetAllApplicantSkill() {
            return base.Channel.GetAllApplicantSkill();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco[]> GetAllApplicantSkillAsync() {
            return base.Channel.GetAllApplicantSkillAsync();
        }
        
        public void UpdateApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] pocos) {
            base.Channel.UpdateApplicantSkill(pocos);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] pocos) {
            return base.Channel.UpdateApplicantSkillAsync(pocos);
        }
        
        public void RemoveApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] pocos) {
            base.Channel.RemoveApplicantSkill(pocos);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] pocos) {
            return base.Channel.RemoveApplicantSkillAsync(pocos);
        }
        
        public void AddApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos) {
            base.Channel.AddApplicantWorkHistory(pocos);
        }
        
        public System.Threading.Tasks.Task AddApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos) {
            return base.Channel.AddApplicantWorkHistoryAsync(pocos);
        }
        
        public CareerCloud.Pocos.ApplicantWorkHistoryPoco GetSingleApplicantWorkHistory(string id) {
            return base.Channel.GetSingleApplicantWorkHistory(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco> GetSingleApplicantWorkHistoryAsync(string id) {
            return base.Channel.GetSingleApplicantWorkHistoryAsync(id);
        }
        
        public CareerCloud.Pocos.ApplicantWorkHistoryPoco[] GetAllApplicantWorkHistory() {
            return base.Channel.GetAllApplicantWorkHistory();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco[]> GetAllApplicantWorkHistoryAsync() {
            return base.Channel.GetAllApplicantWorkHistoryAsync();
        }
        
        public void UpdateApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos) {
            base.Channel.UpdateApplicantWorkHistory(pocos);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos) {
            return base.Channel.UpdateApplicantWorkHistoryAsync(pocos);
        }
        
        public void RemoveApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos) {
            base.Channel.RemoveApplicantWorkHistory(pocos);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] pocos) {
            return base.Channel.RemoveApplicantWorkHistoryAsync(pocos);
        }
    }
}
